sculpin_content_types:
    posts:
        permalink: blog/:year/:month/:day/:filename/
        layout: default
    videos:
        permalink: videos/:filename
        type: path
        path: _videos
        layout: video
        taxonomies:
            - tags
            - categories
