sculpin_content_types:
    posts:
        permalink: blog/:year/:month/:day/:filename/
        layout: default
    videos:
        permalink: videos/:year/:month/:day/:filename/
        type: path
        path: _videos
        layout: video
